// Standalone regression suite. Run: node scripts/regression-tests.cjs [case] [case arguments...]
// Each case runs in its own process so PHP mocks and browser state stay isolated.
const { spawnSync } = require('node:child_process');
const cases = [
  {
    "name": "sitemap-submission",
    "runtime": "php",
    "source": [
      "<?php",
      "define('ABSPATH', '/tmp/');",
      "$options = array('seo_sitemap_path' => 'sitemap.xml', 'sitemap_google_property' => 'sc-domain:example.com', 'sitemap_google_access_token' => 'google-token', 'sitemap_bing_access_token' => 'bing-token');",
      "$requests = array();",
      "class WP_Error { private $message; function __construct($code = '', $message = '') { $this->message = $message; } function get_error_message() { return $this->message; } }",
      "function __($value) { return $value; }",
      "function tk_get_option($key, $default = null) { return $GLOBALS['options'][$key] ?? $default; }",
      "function home_url($path = '/') { return 'https://example.com' . $path; }",
      "function untrailingslashit($value) { return rtrim($value, '/'); }",
      "function wp_json_encode($value) { return json_encode($value); }",
      "function wp_remote_request($url, $args) { $GLOBALS['requests']['google'] = array($url, $args); return array('response' => array('code' => 204)); }",
      "function wp_remote_post($url, $args) { $GLOBALS['requests']['bing'] = array($url, $args); return array('response' => array('code' => 200)); }",
      "function wp_remote_retrieve_response_code($response) { return (int) ($response['response']['code'] ?? 0); }",
      "function is_wp_error($value) { return $value instanceof WP_Error; }",
      "require dirname(__DIR__) . '/includes/general.php';",
      "$sitemap = tk_general_sitemap_url();",
      "$google = tk_general_sitemap_submission_result('google', tk_general_sitemap_submit_google($sitemap));",
      "$bing = tk_general_sitemap_submission_result('bing', tk_general_sitemap_submit_bing($sitemap));",
      "if (!$google['ok'] || strpos($requests['google'][0], rawurlencode('sc-domain:example.com')) === false || $requests['google'][1]['method'] !== 'PUT' || $requests['google'][1]['headers']['Authorization'] !== 'Bearer google-token') { throw new RuntimeException('Google sitemap request mismatch'); }",
      "$bing_body = json_decode($requests['bing'][1]['body'], true);",
      "if (!$bing['ok'] || $requests['bing'][1]['headers']['Authorization'] !== 'Bearer bing-token' || $bing_body['siteUrl'] !== 'https://example.com' || $bing_body['feedUrl'] !== 'https://example.com/sitemap.xml') { throw new RuntimeException('Bing sitemap request mismatch'); }",
      "$failed = tk_general_sitemap_submission_result('google', array('response' => array('code' => 401)));",
      "if ($failed['ok'] || $failed['status'] !== 401) { throw new RuntimeException('Failed submission was not recorded'); }",
      "echo \"PASS: Google and Bing sitemap submissions use authenticated provider requests\\n\";"
    ]
  },
  {
    "name": "faqpage-import",
    "runtime": "php",
    "source": [
      "<?php",
      "define('ABSPATH', '/tmp/');",
      "class WP_Error { public $code; private $message; function __construct($code = '', $message = '') { $this->code = $code; $this->message = $message; } function get_error_message() { return $this->message; } }",
      "function __($value) { return $value; }",
      "function wp_strip_all_tags($value) { return strip_tags($value); }",
      "function get_bloginfo($key) { return $key === 'language' ? 'id_ID' : ''; }",
      "require dirname(__DIR__) . '/includes/geo.php';",
      "$json = json_encode(array('@context' => 'https://schema.org', '@graph' => array(",
      "    array('@type' => 'FAQPage', 'inLanguage' => 'id_ID', 'mainEntity' => array(",
      "        array('@type' => 'Question', 'name' => 'Apa ini?', 'acceptedAnswer' => array('@type' => 'Answer', 'text' => '<p>Jawaban</p>')),",
      "        array('@type' => 'Question', 'name' => 'English?', 'inLanguage' => 'en-US', 'acceptedAnswer' => array('@type' => 'Answer', 'text' => 'Answer')),",
      "    )),",
      "    array('@type' => 'FAQPage', 'mainEntity' => array(",
      "        array('@type' => 'Question', 'name' => 'Fallback?', 'acceptedAnswer' => array('@type' => 'Answer', 'text' => 'Indonesia')),",
      "    )),",
      ")));",
      "$items = tk_geo_import_faqpage_json($json, 'id_ID');",
      "if ($items instanceof WP_Error || count($items) !== 3) { throw new RuntimeException('FAQPage graph import failed'); }",
      "if ($items[0]['language'] !== 'id-id' || $items[0]['answer'] !== 'Jawaban' || $items[1]['language'] !== 'en-us' || $items[2]['language'] !== 'id-id') { throw new RuntimeException('FAQ locale mapping failed'); }",
      "$invalid = tk_geo_import_faqpage_json('{broken', 'id_ID');",
      "if (!($invalid instanceof WP_Error)) { throw new RuntimeException('Invalid FAQ JSON was accepted'); }",
      "echo \"PASS: FAQPage JSON-LD import maps declared and fallback locales\\n\";"
    ]
  },
  {
    "name": "duplicate-content",
    "runtime": "php",
    "source": [
      "<?php",
      "define('ABSPATH', '/tmp/');",
      "$inserted = array(); $terms = array(); $meta = array(); $language = array();",
      "class WP_Error { private $message; function __construct($code = '', $message = '') { $this->message = $message; } function get_error_message() { return $this->message; } }",
      "function __($value) { return $value; }",
      "function is_wp_error($value) { return $value instanceof WP_Error; }",
      "function get_post($id) { return (object) array('ID' => $id, 'post_author' => 4, 'post_content' => '<!-- wp:paragraph --><p>Body</p><!-- /wp:paragraph -->', 'post_content_filtered' => '', 'post_excerpt' => 'Excerpt', 'post_title' => 'Source', 'post_type' => 'page', 'comment_status' => 'closed', 'ping_status' => 'closed', 'post_password' => '', 'post_parent' => 8, 'menu_order' => 2); }",
      "function wp_insert_post($data, $wp_error = false) { $GLOBALS['inserted'] = $data; return 42; }",
      "function get_object_taxonomies($type) { return array('category', 'language', 'post_translations'); }",
      "function wp_get_object_terms($id, $taxonomy, $args) { return array(3, 5); }",
      "function wp_set_object_terms($id, $terms, $taxonomy) { $GLOBALS['terms'] = array($id, $terms, $taxonomy); }",
      "function get_post_meta($id) { return array('_thumbnail_id' => array('9'), '_edit_lock' => array('old-lock'), 'custom_key' => array('i:123;')); }",
      "function maybe_unserialize($value) { $decoded = @unserialize($value); return $decoded === false ? $value : $decoded; }",
      "function add_post_meta($id, $key, $value) { $GLOBALS['meta'][$key][] = $value; }",
      "function pll_get_post_language($id, $field) { return 'id'; }",
      "function pll_set_post_language($id, $language) { $GLOBALS['language'] = array($id, $language); }",
      "require dirname(__DIR__) . '/includes/general.php';",
      "$duplicate_id = tk_general_duplicate_post(12);",
      "if ($duplicate_id !== 42 || $inserted['post_status'] !== 'draft' || $inserted['post_title'] !== 'Copy of Source' || $inserted['post_parent'] !== 8) { throw new RuntimeException('Duplicate draft fields mismatch'); }",
      "if ($terms !== array(42, array(3, 5), 'category')) { throw new RuntimeException('Taxonomies were not copied'); }",
      "if (isset($meta['_edit_lock']) || $meta['_thumbnail_id'][0] !== '9' || $meta['custom_key'][0] !== 123) { throw new RuntimeException('Post metadata copy mismatch'); }",
      "if ($language !== array(42, 'id')) { throw new RuntimeException('Source language was not preserved independently'); }",
      "echo \"PASS: duplicate creates a draft with taxonomy and safe metadata copies\\n\";"
    ]
  },
  {
    "name": "login-first-hit",
    "runtime": "php",
    "source": [
      "<?php",
      "define('ABSPATH', '/tmp/');",
      "$options = array('security_login_error_obfuscation_enabled' => 1, 'captcha_enabled' => 1, 'captcha_on_login' => 1);",
      "$locale = 'en_US';",
      "function add_action(...$args) {}",
      "function add_filter(...$args) {}",
      "function add_shortcode(...$args) {}",
      "function shortcode_atts($defaults, $atts, $shortcode = '') { return array_merge($defaults, $atts); }",
      "function sanitize_key($value) { return strtolower(preg_replace('/[^a-z0-9_\\-]/', '', (string) $value)); }",
      "function determine_locale() { return $GLOBALS['locale']; }",
      "function tk_get_option($key, $default = null) { return $GLOBALS['options'][$key] ?? $default; }",
      "function wp_strip_all_tags($value) { return strip_tags($value); }",
      "function __($value) { return $value; }",
      "require dirname(__DIR__) . '/includes/security-login-log.php';",
      "require dirname(__DIR__) . '/includes/security-captcha.php';",
      "$user = (object) array('ID' => 7);",
      "$classic_tag = (object) array('options' => array('clasic=\"1\"'));",
      "$robot_tag = (object) array('options' => array('robot:1'));",
      "if (tk_captcha_type_from_wpcf7_tag($classic_tag) !== 'text') { throw new RuntimeException('CF7 clasic parameter did not select text CAPTCHA'); }",
      "if (tk_captcha_type_from_wpcf7_tag($robot_tag) !== 'checkbox') { throw new RuntimeException('CF7 robot parameter did not select checkbox CAPTCHA'); }",
      "if (tk_captcha_text('enter_code') !== 'Enter the code below') { throw new RuntimeException('English CAPTCHA text mismatch'); }",
      "$locale = 'id_ID';",
      "if (tk_captcha_text('enter_code') !== 'Masukkan kode di bawah ini' || tk_captcha_text('not_robot') !== 'Saya bukan robot') { throw new RuntimeException('Indonesian CAPTCHA text mismatch'); }",
      "$_POST = array();",
      "if (tk_login_security_obfuscate_errors('Cookies must be enabled.') !== 'Cookies must be enabled.') { throw new RuntimeException('GET login message was obfuscated'); }",
      "if (tk_captcha_validate($user) !== $user) { throw new RuntimeException('GET login request was treated as a CAPTCHA failure'); }",
      "$_POST = array('log' => 'member', 'pwd' => 'wrong');",
      "if (tk_login_security_obfuscate_errors('Unknown username.') !== 'Login failed.') { throw new RuntimeException('POST authentication error was not obfuscated'); }",
      "echo \"PASS: first hide-login hit stays informational and does not trigger CAPTCHA failure\\n\";"
    ]
  },
  {
    "name": "geo-saved-results",
    "runtime": "php",
    "source": [
      "<?php",
      "define('ABSPATH', '/tmp/');",
      "$saved = array('url' => 'https://example.com/', 'status' => 200, 'score' => 90); $calls = 0;",
      "class WP_Error { function get_error_message() { return 'cURL error 28: timeout'; } }",
      "function tk_get_option($key, $default = null) { return $key === 'seo_geo_audit_report' ? array('items' => array($GLOBALS['saved'])) : $default; }",
      "function wp_remote_get($url, $args) { $GLOBALS['calls']++; return new WP_Error(); }",
      "function is_wp_error($value) { return $value instanceof WP_Error; }",
      "require dirname(__DIR__) . '/includes/seo-optimization.php';",
      "if (tk_seo_geo_audit_url($saved['url']) !== $saved || $calls !== 0) { throw new RuntimeException('Saved success must not crawl'); }",
      "$saved['status'] = 0; $saved['score'] = null;",
      "if (tk_seo_geo_audit_url($saved['url']) !== $saved || $calls !== 0) { throw new RuntimeException('Saved failure must not automatically retry'); }",
      "tk_seo_geo_audit_url($saved['url'], 20, true);",
      "if ($calls !== 1) { throw new RuntimeException('Explicit retry must crawl once'); }",
      "tk_seo_geo_audit_url('https://example.com/new');",
      "if ($calls !== 2) { throw new RuntimeException('New URL must crawl'); }",
      "echo \"PASS: saved success/failure reuse, explicit retry and new URL requests\\n\";"
    ]
  },
  {
    "name": "preload-failure-backoff",
    "runtime": "php",
    "source": [
      "<?php",
      "define('ABSPATH', '/tmp/'); define('MINUTE_IN_SECONDS', 60);",
      "$cooldown = false; $calls = 0;",
      "function get_transient($key) { return $GLOBALS['cooldown']; }",
      "function set_transient($key, $value, $ttl) { $GLOBALS['cooldown'] = $value; }",
      "function home_url($path) { return 'https://example.com' . $path; }",
      "function get_post_types($args, $format) { return array(); }",
      "function tk_get_option($key, $default = null) { return $default; }",
      "function wp_parse_url($url, $component) { return parse_url($url, $component); }",
      "function esc_url_raw($url) { return $url; }",
      "function wp_remote_get($url, $args) { $GLOBALS['calls']++; return new stdClass(); }",
      "function is_wp_error($response) { return true; }",
      "require dirname(__DIR__) . '/includes/cache.php';",
      "$first = tk_cache_preload_run(); $second = tk_cache_preload_run();",
      "if ($calls !== 1 || $first['failed'] !== 1 || $second['urls'] !== 0) { throw new RuntimeException('Preloader must back off after failure'); }",
      "echo \"PASS: preload stops on failure and repeated request respects cooldown\\n\";"
    ]
  },
  {
    "name": "geo-report-cache-purge",
    "runtime": "php",
    "source": [
      "<?php",
      "define('ABSPATH', '/tmp/');",
      "$hooks = array();",
      "function add_action($hook, $callback, $priority = 10) { $GLOBALS['hooks'][] = array($hook, $callback); }",
      "require dirname(__DIR__) . '/includes/cache.php';",
      "$old = array('geo_enabled' => 1, 'geo_faq_items' => array('question' => 'Old'), 'seo_geo_audit_report' => array());",
      "$new = $old; $new['seo_geo_audit_report'] = array('items' => array('new result'));",
      "tk_page_cache_purge_on_updated_option('tk_options', $old, $new);",
      "$new['geo_ai_access_report'] = array('status' => 'checked'); $new['authority_reports'] = array('status' => 'checked');",
      "tk_page_cache_purge_on_updated_option('tk_options', $old, $new);",
      "unset($new['seo_geo_audit_report']);",
      "tk_page_cache_purge_on_updated_option('tk_options', $old, $new);",
      "if ($hooks) { throw new RuntimeException('Admin report changes purged page cache'); }",
      "$new['geo_faq_items'] = array('question' => 'Updated');",
      "tk_page_cache_purge_on_updated_option('tk_options', $old, $new);",
      "if ($hooks !== array(array('shutdown', 'tk_page_cache_purge'))) { throw new RuntimeException('Real content/settings changes must purge cache'); }",
      "echo \"PASS: report updates/removals preserve cache; mixed FAQ/settings updates invalidate cache\\n\";"
    ]
  },
  {
    "name": "asset-hash-cache",
    "runtime": "php",
    "source": [
      "<?php",
      "define('ABSPATH', '/tmp/');",
      "$cache = array();",
      "$writes = 0;",
      "function get_transient($key) { return $GLOBALS['cache'][$key] ?? false; }",
      "function set_transient($key, $value, $ttl) {",
      "    if ($ttl !== 60) { throw new RuntimeException('Unexpected cache TTL'); }",
      "    $GLOBALS['cache'][$key] = $value;",
      "    $GLOBALS['writes']++;",
      "}",
      "require dirname(__DIR__) . '/includes/asset-optimization.php';",
      "$file = tempnam(sys_get_temp_dir(), 'tk-hash-');",
      "try {",
      "    file_put_contents($file, 'first asset');",
      "    clearstatcache(true, $file);",
      "    $first = tk_assets_cached_file_hash($file);",
      "    if ($first !== hash_file('sha256', $file)) { throw new RuntimeException('Initial hash mismatch'); }",
      "    tk_assets_cached_file_hash($file);",
      "    if ($writes !== 1) { throw new RuntimeException('Hash not cached'); }",
      "    file_put_contents($file, 'updated longer asset');",
      "    clearstatcache(true, $file);",
      "    $next = tk_assets_cached_file_hash($file);",
      "    if ($first === $next || $writes !== 2) { throw new RuntimeException('Changed file not detected'); }",
      "    $cache = array();",
      "    tk_assets_cached_file_hash($file);",
      "    if ($writes !== 3) { throw new RuntimeException('Expired cache not recomputed'); }",
      "    echo \"PASS: hash reuse, file changes, cache expiry\\n\";",
      "} finally { unlink($file); }",
      ""
    ]
  },
  {
    "name": "external-authority",
    "runtime": "php",
    "source": [
      "<?php",
      "define('ABSPATH', '/tmp/');",
      "function wp_parse_url($url, $component = -1) { return parse_url($url, $component); }",
      "function home_url($path) { return 'https://brand.example/'; }",
      "require dirname(__DIR__) . '/includes/external-authority.php';",
      "function verify($condition) { if (!$condition) { throw new RuntimeException('Authority regression'); } }",
      "verify(!tk_authority_external_url('https://brand.example/page'));",
      "verify(!tk_authority_external_url('https://shop.brand.example/page'));",
      "verify(!tk_authority_external_url('https://www.brand.example/page'));",
      "verify(tk_authority_external_url('https://publisher.example/story'));",
      "$report = tk_authority_parse_evidence('<html><body>Brand Name <a href=\"https://www.brand.example/about\" rel=\"nofollow\">Website</a></body></html>', 'Brand Name', home_url('/'));",
      "verify($report['brand_mention'] && count($report['links']) === 1 && $report['links'][0]['rel'] === 'nofollow');",
      "$report = tk_authority_parse_evidence('<html><head><title>Brand Name</title></head><body><script>Brand Name</script><p>Brand Namesake</p><a href=\"https://brand.example.evil.test\">Other</a></body></html>', 'Brand Name', home_url('/'));",
      "verify(!$report['brand_mention'] && !$report['links'] && $report['status'] === 'not-verified');",
      "echo \"PASS: external origins, mentions, domain links, rel, false positives\\n\";",
      ""
    ]
  },
  {
    "name": "geo-batch-ui",
    "runtime": "node",
    "source": [
      "const assert = require('node:assert/strict');",
      "const fs = require('node:fs');",
      "const vm = require('node:vm');",
      "",
      "function control() {",
      "    return { listeners: {}, addEventListener(event, fn) { this.listeners[event] = fn; }, textContent: '', disabled: false };",
      "}",
      "async function test(readyState) {",
      "    const controls = {};",
      "    ['.tk-geo-run-all', '.tk-geo-run-selected', '.tk-geo-stop', '.tk-geo-status', 'progress', '.tk-geo-batch-results', '.tk-geo-select-all', '.tk-geo-report-status', '.tk-geo-report-selected', '.tk-geo-retry-failed'].forEach(key => { controls[key] = control(); });",
      "    controls['.tk-geo-batch-results'].replaceChildren = () => {};",
      "    controls['.tk-geo-batch-results'].appendChild = () => {};",
      "    const root = { dataset: { nonce: 'test', endpoint: '/ajax' }, querySelector: key => controls[key], querySelectorAll: () => [] };",
      "    let ready;",
      "    const calls = [];",
      "    let reloads = 0;",
      "    const document = {",
      "        readyState,",
      "        getElementById: () => root,",
      "        querySelector: key => controls[key],",
      "        querySelectorAll: key => ['.tk-geo-report-selected', '.tk-geo-retry-failed'].includes(key) ? [controls[key]] : [],",
      "        addEventListener: (event, fn) => { ready = fn; },",
      "        createElement: () => ({ style: {} })",
      "    };",
      "    vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname, '../assets/geo-audit-batch.js'), 'utf8'), {",
      "        document, URL, URLSearchParams, AbortController, setTimeout, clearTimeout,",
      "        window: { location: { href: 'https://example.com/wp-admin/admin.php?page=tool-kits-geo', replace(url) {",
      "            const target = new URL(url);",
      "            assert.equal(target.searchParams.get('page'), 'tool-kits-geo');",
      "            assert.ok(target.searchParams.get('tk_geo_refresh'));",
      "            assert.equal(target.hash, '#geo-audit');",
      "            reloads++;",
      "        } } },",
      "        fetch: async (url, options) => {",
      "            calls.push(options.body.get('action'));",
      "            return { ok: true, json: async () => ({ success: true, data: calls.length === 1 ? { token: 'test', total: 1 } : { done: true, checked: 1, total: 1 } }) };",
      "        }",
      "    });",
      "    if (readyState === 'loading') {",
      "        assert.equal(controls['.tk-geo-retry-failed'].listeners.click, undefined);",
      "        ready();",
      "    }",
      "    controls['.tk-geo-report-selected'].listeners.click();",
      "    assert.match(controls['.tk-geo-report-status'].textContent, /Select at least/);",
      "    controls['.tk-geo-retry-failed'].listeners.click();",
      "    assert.equal(controls['.tk-geo-report-status'].textContent, 'Starting audit...');",
      "    await new Promise(resolve => setImmediate(resolve));",
      "    assert.deepEqual(calls, ['tk_geo_batch_start', 'tk_geo_batch_step']);",
      "    assert.match(controls['.tk-geo-report-status'].textContent, /Completed: 1\\/1/);",
      "    assert.equal(reloads, 1);",
      "}",
      "(async () => {",
      "    await test('loading');",
      "    await test('complete');",
      "    console.log('PASS: DOM readiness, report button handlers, local status and AJAX start/step');",
      "})().catch(error => { console.error(error); process.exitCode = 1; });",
      ""
    ]
  },
  {
    "name": "geo-batch",
    "runtime": "php",
    "source": [
      "<?php",
      "define('ABSPATH', '/tmp/');",
      "define('HOUR_IN_SECONDS', 3600);",
      "$cache = array();",
      "$timeouts = array();",
      "function home_url($path) { return 'https://example.com/'; }",
      "function get_post_types($args, $format) { return array('page'); }",
      "function tk_seo_selected_post_types() { return array('page'); }",
      "function get_posts($args) { return array((object) array('ID' => 1, 'post_type' => 'page')); }",
      "function is_post_type_viewable($type) { return true; }",
      "function get_permalink($id) { return 'https://example.com/page'; }",
      "function get_the_title($post) { return 'Page'; }",
      "function check_ajax_referer($action) {}",
      "function tk_is_admin_user() { return true; }",
      "function tk_license_features_enabled() { return true; }",
      "function absint($id) { return abs((int) $id); }",
      "function wp_generate_password($length, $special, $extra) { return str_repeat('A', 24); }",
      "function get_current_user_id() { return 1; }",
      "function set_transient($key, $value, $ttl) { $GLOBALS['cache'][$key] = $value; }",
      "function get_transient($key) { return $GLOBALS['cache'][$key] ?? false; }",
      "function delete_transient($key) { unset($GLOBALS['cache'][$key]); }",
      "function tk_update_option($key, $value) { $GLOBALS['report'] = $value; }",
      "function tk_get_option($key, $default) { return $GLOBALS['report'] ?? $default; }",
      "function tk_seo_geo_audit_summary($items) { return array('average_score' => 0, 'issue_count' => 0); }",
      "function tk_seo_geo_audit_url($url, $timeout) { $GLOBALS['timeouts'][] = $timeout; return array('url' => $url, 'status' => 0, 'score' => null, 'issues' => array('Timeout')); }",
      "class BatchResponse extends RuntimeException { public $data; public function __construct($data) { $this->data = $data; } }",
      "function wp_send_json_success($data) { throw new BatchResponse($data); }",
      "function wp_send_json_error($data, $status) { throw new RuntimeException($data['message']); }",
      "require dirname(__DIR__) . '/includes/geo-audit-batch.php';",
      "function invoke($function) { try { $function(); } catch (BatchResponse $response) { return $response->data; } throw new RuntimeException('Missing response'); }",
      "function verify($condition) { if (!$condition) { throw new RuntimeException('Batch regression'); } }",
      "$_POST = array('mode' => 'all');",
      "$session = invoke('tk_geo_batch_start');",
      "verify($session['total'] === 2);",
      "$_POST = array('token' => $session['token']);",
      "$first = invoke('tk_geo_batch_step');",
      "verify(!$first['done'] && $first['checked'] === 1 && $report['incomplete']);",
      "$second = invoke('tk_geo_batch_step');",
      "verify($second['done'] && $second['checked'] === 2 && !$report['incomplete']);",
      "verify($timeouts === array(20, 20));",
      "$_POST = array('mode' => 'selected', 'ids' => array('1', '999'));",
      "$session = invoke('tk_geo_batch_start');",
      "verify($session['total'] === 1);",
      "$report = array('requested_urls' => 2, 'items' => array(",
      "    array('url' => home_url('/'), 'status' => 0, 'score' => null),",
      "    array('url' => get_permalink(1), 'status' => 200, 'score' => 90),",
      "));",
      "$_POST = array('mode' => 'failed');",
      "$session = invoke('tk_geo_batch_start');",
      "verify($session['total'] === 1);",
      "$_POST = array('token' => $session['token']);",
      "invoke('tk_geo_batch_step');",
      "verify(count($report['items']) === 2 && $report['items'][1]['score'] === 90);",
      "$_POST = array('mode' => 'report-selected', 'urls' => array(get_permalink(1), 'https://invalid.example/'));",
      "$session = invoke('tk_geo_batch_start');",
      "verify($session['total'] === 1);",
      "echo \"PASS: all/selected targets, one URL per step, full timeouts, continue after failure, saved progress\\n\";",
      ""
    ]
  },
  {
    "name": "geo-timeout",
    "runtime": "php",
    "source": [
      "<?php",
      "define('ABSPATH', '/tmp/');",
      "class WP_Error { public function get_error_message() { return 'cURL error 28: timed out'; } }",
      "$calls = 0;",
      "function wp_remote_get($url, $args) { $GLOBALS['calls']++; $GLOBALS['timeout'] = $args['timeout']; return new WP_Error(); }",
      "function is_wp_error($value) { return $value instanceof WP_Error; }",
      "function home_url($path) { return 'https://example.com/'; }",
      "function get_post_types($args, $format) { return array('page'); }",
      "function get_posts($args) { return array(1, 2); }",
      "function get_permalink($id) { return 'https://example.com/page-' . $id; }",
      "require dirname(__DIR__) . '/includes/seo-optimization.php';",
      "$report = tk_seo_run_geo_audit();",
      "if ($calls !== 1 || $timeout !== 20 || !$report['incomplete'] || $report['items'][0]['score'] !== null || $report['items'][0]['grade'] !== '-') {",
      "    throw new RuntimeException('Timeout handling regression');",
      "}",
      "$summary = tk_seo_geo_audit_summary(array($report['items'][0], array('score' => 80, 'issues' => array())));",
      "if (strpos($report['items'][0]['issues'][0], 'Transport error: cURL error 28: timed out') === false) { throw new RuntimeException('Transport diagnostics must be preserved'); }",
      "if ($summary['average_score'] !== 80) { throw new RuntimeException('Unverified pages must not reduce score'); }",
      "echo \"PASS: 20-second timeout, stop on network failure, unverified score exclusion\\n\";",
      ""
    ]
  },
  {
    "name": "image-optimizer-no-imagick",
    "runtime": "php",
    "source": [
      "<?php",
      "declare(strict_types=1);",
      "if (class_exists('Imagick') || !extension_loaded('gd')) {",
      "    fwrite(STDERR, \"Run with a PHP binary that has GD and no Imagick.\\n\");",
      "    exit(1);",
      "}",
      "define('ABSPATH', __DIR__ . '/');",
      "$test_dir = sys_get_temp_dir() . '/tkopt-gd-test-' . bin2hex(random_bytes(6));",
      "mkdir($test_dir);",
      "function tk_get_option($key, $default = null) { return $default; }",
      "function wp_get_upload_dir() { return array('basedir' => $GLOBALS['test_dir']); }",
      "require dirname(__DIR__) . '/includes/image-optimizer-engine.php';",
      "$source = $test_dir . '/source.png';",
      "try {",
      "    $image = imagecreatetruecolor(64, 64);",
      "    imagepng($image, $source); imagedestroy($image);",
      "    $hash = hash_file('sha256', $source);",
      "    $result = tk_image_opt_encode($source, $test_dir . '/source-tkopt.png', 95);",
      "    if ($result['optimized'] || strpos($result['reason'], 'requires Imagick') === false",
      "        || hash_file('sha256', $source) !== $hash || count(glob($test_dir . '/*')) !== 1) {",
      "        throw new RuntimeException('No-Imagick fallback failed.');",
      "    }",
      "    echo \"[PASS] Missing Imagick preserves original and reports unavailable Hi-Res verification.\\n\";",
      "} finally {",
      "    foreach (glob($test_dir . '/*') as $file) { unlink($file); }",
      "    rmdir($test_dir);",
      "}",
      ""
    ]
  },
  {
    "name": "image-optimizer",
    "runtime": "php",
    "source": [
      "<?php",
      "// Standalone integration tests: real image codecs and optional WordPress HTML parser.",
      "// php scripts/test-image-optimizer.php /path/to/wordpress [/path/to/sRGB.icc]",
      "declare(strict_types=1);",
      "",
      "if (!extension_loaded('imagick')) {",
      "    fwrite(STDERR, \"Imagick is required for the codec regression tests.\\n\");",
      "    exit(1);",
      "}",
      "define('ABSPATH', __DIR__ . '/');",
      "$test_dir = sys_get_temp_dir() . '/tkopt-test-' . bin2hex(random_bytes(6));",
      "mkdir($test_dir);",
      "$test_dir = realpath($test_dir);",
      "$test_options = array('image_opt_enabled' => 1, 'image_opt_frontend_optimize' => 1);",
      "$test_files = array();",
      "$test_metadata = array();",
      "$passes = 0;",
      "",
      "// Isolate filesystem and settings from any real site/database.",
      "function tk_get_option($key, $default = null) { return $GLOBALS['test_options'][$key] ?? $default; }",
      "function tk_update_option($key, $value) { $GLOBALS['test_options'][$key] = $value; }",
      "function tk_license_features_enabled() { return true; }",
      "function is_admin() { return false; }",
      "function wp_get_upload_dir() { return array('basedir' => $GLOBALS['test_dir'], 'baseurl' => 'https://cdn.example.test/site/uploads'); }",
      "function wp_parse_url($url, $component = -1) { return parse_url($url, $component); }",
      "function wp_json_encode($value) { return json_encode($value); }",
      "function wp_normalize_path($path) { return str_replace('\\\\', '/', $path); }",
      "function trailingslashit($value) { return rtrim($value, '/') . '/'; }",
      "function get_attached_file($id) { return $GLOBALS['test_files'][$id] ?? ''; }",
      "function wp_get_attachment_metadata($id) { return $GLOBALS['test_metadata'][$id] ?? array(); }",
      "function update_post_meta($id, $key, $value) {",
      "    if (!empty($GLOBALS['test_stop_worker'])) {",
      "        $GLOBALS['test_options']['image_opt_queue']['status'] = 'stopped';",
      "    }",
      "}",
      "function get_post_mime_type($id) { return 'image/jpeg'; }",
      "function attachment_url_to_postid($url) {",
      "    foreach ($GLOBALS['test_files'] as $id => $file) {",
      "        if (tk_image_opt_path_to_upload_url($file) === $url) { return $id; }",
      "    }",
      "    return 0;",
      "}",
      "function add_query_arg($key, $value, $url) { return $url . (strpos($url, '?') === false ? '?' : '&') . urlencode($key) . '=' . urlencode($value); }",
      "function esc_attr($value) { return htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }",
      "function esc_url($value) { return esc_attr($value); }",
      "function wp_kses_uri_attributes() { return array('src', 'href'); }",
      "function _doing_it_wrong($function, $message, $version) { throw new RuntimeException($function . ': ' . $message); }",
      "function __($value) { return $value; }",
      "function wp_cache_delete($key, $group) {}",
      "function wp_next_scheduled($hook) { return false; }",
      "function wp_schedule_single_event($time, $hook) { $GLOBALS['test_scheduled'][] = $hook; }",
      "function get_the_title($id) { return 'Test ' . $id; }",
      "function wp_get_attachment_url($id) { return tk_image_opt_path_to_upload_url(get_attached_file($id)); }",
      "class WP_Query {",
      "    public $posts;",
      "    public $found_posts;",
      "    public function __construct($args) {",
      "        $ids = array_keys($GLOBALS['test_files']); sort($ids);",
      "        $this->found_posts = count($ids);",
      "        $this->posts = array_slice($ids, $args['offset'] ?? 0, $args['posts_per_page']);",
      "    }",
      "}",
      "",
      "require dirname(__DIR__) . '/includes/image-optimizer.php';",
      "require dirname(__DIR__) . '/includes/webp.php';",
      "",
      "function check(bool $ok, string $message): void {",
      "    if (!$ok) { throw new RuntimeException($message); }",
      "    $GLOBALS['passes']++;",
      "    echo '[PASS] ', $message, PHP_EOL;",
      "}",
      "function pixels(string $path): string {",
      "    $image = new Imagick($path);",
      "    $signature = tk_image_opt_pixel_signature($image);",
      "    $image->clear();",
      "    return $signature;",
      "}",
      "function fixture(string $path, string $format, int $width = 3200, int $height = 1800): void {",
      "    $image = new Imagick();",
      "    $image->newPseudoImage($width, $height, 'gradient:#153728-#faf7fe');",
      "    $draw = new ImagickDraw();",
      "    $draw->setFillColor('#e72846');",
      "    for ($x = 0; $x < $width; $x += 53) {",
      "        $draw->rectangle($x, 30, $x + 2, $height - 30);",
      "    }",
      "    $image->drawImage($draw);",
      "    $image->setImageDepth(8);",
      "    $image->setImageFormat($format);",
      "    $image->setImageCompressionQuality(100);",
      "    $image->setImageProperty('comment', str_repeat('removable test metadata ', 2000));",
      "    if (!empty($GLOBALS['argv'][2]) && $format === 'jpeg') {",
      "        $image->profileImage('icc', file_get_contents($GLOBALS['argv'][2]));",
      "    }",
      "    $image->writeImage($path);",
      "    $image->clear();",
      "}",
      "",
      "try {",
      "    $source = $test_dir . '/photo.jpg';",
      "    $target = $test_dir . '/photo-tkopt.jpg';",
      "    fixture($source, 'jpeg');",
      "    $hash = hash_file('sha256', $source);",
      "    check(tk_image_opt_frontend_url(tk_image_opt_path_to_upload_url($source)) === tk_image_opt_path_to_upload_url($source)",
      "        && !is_file($target), 'Missing derivative uses source without frontend generation');",
      "    $test_options['image_opt_max_width'] = 768;",
      "    $test_options['image_opt_max_height'] = 549;",
      "    $result = tk_image_opt_create_optimized_derivative($source, $target, 30);",
      "    check($result['optimized'], 'JPEG generates a smaller validated derivative');",
      "    check(array_slice(getimagesize($target), 0, 2) === array(3200, 1800), 'Hi-Res ignores legacy resize limits');",
      "    check(hash_file('sha256', $source) === $hash, 'Original upload remains byte-for-byte unchanged');",
      "    $report = json_decode(file_get_contents($target . '.json'), true);",
      "    check($report['quality'] === 95 && $report['dpi_applied'], 'Hi-Res clamps old low quality to 95 and applies DPI');",
      "    $before = new Imagick($source);",
      "    $after = new Imagick($target);",
      "    $dpi = $after->getImageResolution();",
      "    check(abs($dpi['x'] - 72) < 1 && abs($dpi['y'] - 72) < 1, 'DPI set to 72 without resampling');",
      "    check($before->getImageProfiles('icc', true) === $after->getImageProfiles('icc', true), 'ICC profile survives metadata stripping');",
      "    $comparison = $before->compareImages($after, Imagick::METRIC_ROOTMEANSQUAREDERROR);",
      "    $psnr = $comparison[1] > 0 ? -20 * log10($comparison[1]) : INF;",
      "    check($psnr > 35, 'JPEG fixture PSNR exceeds 35 dB (' . round($psnr, 2) . ' dB)');",
      "    $comparison[0]->clear();",
      "    echo 'JPEG fixture: ', filesize($source), ' -> ', filesize($target), \" bytes\\n\";",
      "    $before->clear(); $after->clear();",
      "",
      "    $url = tk_image_opt_path_to_upload_url($source);",
      "    check(strpos(tk_image_opt_frontend_url($url), 'photo-tkopt.jpg?tkopt=') !== false, 'Frontend selects validated derivative with cache revision');",
      "    $test_options['image_opt_target_dpi'] = 96;",
      "    check(tk_image_opt_frontend_url($url) === $url, 'Changed settings immediately fall back to source');",
      "    $test_options['image_opt_target_dpi'] = 72;",
      "    touch($source, time() + 2);",
      "    check(tk_image_opt_frontend_url($url) === $url, 'Changed source invalidates old derivative');",
      "    check(tk_image_opt_create_optimized_derivative($source, $target, 95)['optimized'], 'Regeneration succeeds from the original source');",
      "    $regenerated = hash_file('sha256', $target);",
      "    tk_image_opt_create_optimized_derivative($source, $target, 95);",
      "    check(hash_file('sha256', $target) === $regenerated, 'Repeat generation does not accumulate JPEG loss');",
      "    $test_files[99] = $target;",
      "    check(!tk_image_opt_encode($source, $target, 95)['optimized'] && hash_file('sha256', $target) === $regenerated,",
      "        'A derivative filename registered as another attachment is never overwritten');",
      "    unset($test_files[99]);",
      "",
      "    $png = $test_dir . '/graphic.png';",
      "    $graphic = new Imagick();",
      "    $graphic->newImage(640, 480, new ImagickPixel('transparent'), 'png');",
      "    $graphic->setImageDepth(8);",
      "    $draw = new ImagickDraw(); $draw->setFillColor('rgba(180,20,80,0.5)'); $draw->rectangle(30, 30, 400, 250);",
      "    $graphic->drawImage($draw);",
      "    $graphic->setImageProperty('comment', str_repeat('metadata ', 5000));",
      "    $graphic->writeImage($png); $graphic->clear();",
      "    $png_copy = $test_dir . '/graphic-tkopt.png';",
      "    check(tk_image_opt_create_optimized_derivative($png, $png_copy, 95)['optimized'], 'PNG optimized without lossy quantization');",
      "    check(pixels($png) === pixels($png_copy), 'PNG decoded pixels and alpha are identical');",
      "    $test_options['webp_serve_enabled'] = 1;",
      "    $webp_test = tk_image_opt_encode($source, $source . '-tkopt.webp', 95);",
      "    if ($webp_test['optimized']) {",
      "        check(tk_image_opt_valid_derivative($source, $source . '-tkopt.webp', 95)",
      "            && pixels($source) === pixels($source . '-tkopt.webp'), 'JPEG-to-WebP is accepted only with matching source pixels');",
      "    } else {",
      "        check(!is_file($source . '-tkopt.webp') && !empty($webp_test['reason']), 'JPEG-to-WebP conversion that fails validation leaves no published copy');",
      "        check(strpos(tk_image_opt_frontend_url($url), 'photo-tkopt.jpg') !== false, 'Rejected WebP conversion falls back to validated JPEG');",
      "    }",
      "    tk_image_opt_generate_copies($png, 95);",
      "    check(is_file($png . '-tkopt.webp') && pixels($png) === pixels($png . '-tkopt.webp'), 'PNG-to-WebP preserves decoded pixels and transparency');",
      "    check(tk_image_opt_source_candidates_for_derivative($png . '-tkopt.webp')[0] === $png, 'Source-extension WebP naming resolves to the correct source');",
      "    $test_options['webp_serve_enabled'] = 0;",
      "",
      "    $animated = new Imagick();",
      "    foreach (array('red', 'blue') as $color) {",
      "        $frame = new Imagick(); $frame->newImage(32, 32, $color, 'webp');",
      "        $frame->setImageDelay(20); $animated->addImage($frame); $frame->clear();",
      "    }",
      "    $animation = $test_dir . '/animation.webp';",
      "    $animated->writeImages($animation, true); $animated->clear();",
      "    $animation_hash = hash_file('sha256', $animation);",
      "    check(!tk_image_opt_create_optimized_derivative($animation, $test_dir . '/animation-tkopt.webp', 95)['optimized']",
      "        && hash_file('sha256', $animation) === $animation_hash, 'Animated WebP is left intact instead of flattening frames');",
      "",
      "    $tiny = $test_dir . '/tiny.png';",
      "    $tiny_image = new Imagick(); $tiny_image->newImage(1, 1, 'transparent', 'png');",
      "    $tiny_image->stripImage(); $tiny_image->writeImage($tiny); $tiny_image->clear();",
      "    $tiny_hash = hash_file('sha256', $tiny);",
      "    $tiny_result = tk_image_opt_create_optimized_derivative($tiny, $test_dir . '/tiny-tkopt.png', 95);",
      "    check(!$tiny_result['optimized'] || filesize($tiny_result['path']) < filesize($tiny), 'No output larger than its source is accepted');",
      "    check(hash_file('sha256', $tiny) === $tiny_hash, 'Already small image retains its source');",
      "",
      "    $test_options['image_opt_preserve_hires'] = 0;",
      "    check(tk_image_opt_create_optimized_derivative($source, $target, 95)['optimized']",
      "        && getimagesize($target)[0] === 768, 'Explicitly disabling Hi-Res permits configured resize');",
      "    $test_options['image_opt_preserve_hires'] = 1;",
      "    check(tk_image_opt_frontend_url($url) === $url, 'Hi-Res refuses a previously resized derivative');",
      "    tk_image_opt_create_optimized_derivative($source, $target, 95);",
      "",
      "    $bad = $test_dir . '/broken.jpg'; file_put_contents($bad, 'not an image');",
      "    check(!tk_image_opt_create_optimized_derivative($bad, $test_dir . '/broken-tkopt.jpg', 95)['optimized'], 'Invalid images are rejected');",
      "    check(!tk_image_opt_create_optimized_derivative($source, $source, 95)['optimized'], 'Source replacement is rejected');",
      "    check(!tk_image_opt_create_optimized_derivative($target, $test_dir . '/photo-tkopt-tkopt.jpg', 95)['optimized'], 'Already optimized sources cannot be recompressed');",
      "    check(tk_image_opt_url_to_local_path('https://foreign.test/site/uploads/photo.jpg') === '', 'External origins are rejected');",
      "    check(tk_image_opt_url_to_local_path('https://cdn.example.test/site/uploads/%2e%2e/private.jpg') === '', 'Encoded path traversal is rejected');",
      "    check(tk_image_opt_url_to_local_path('https://cdn.example.test/site/uploads/photo.jpg') === $source, 'Custom uploads URL maps to local uploads correctly');",
      "    $outside = tempnam(sys_get_temp_dir(), 'tkopt-outside-');",
      "    symlink($outside, $test_dir . '/linked.jpg');",
      "    check(tk_image_opt_url_to_local_path('https://cdn.example.test/site/uploads/linked.jpg') === '', 'Symlinks outside uploads are rejected');",
      "    unlink($test_dir . '/linked.jpg'); unlink($outside);",
      "",
      "    $scaled = $test_dir . '/photo-scaled.jpg'; copy($source, $scaled);",
      "    $test_files[1] = $scaled;",
      "    $test_metadata[1] = array('original_image' => 'photo.jpg', 'sizes' => array('medium' => array('file' => 'photo-768x432.jpg')));",
      "    check(tk_image_opt_source_file(1) === $source, 'WordPress scaled attachments use original high-resolution upload');",
      "    $native_src = tk_image_opt_filter_image_src(array($url, 768, 432, true), 1, 'medium', false);",
      "    check($native_src[1] === 3200 && $native_src[2] === 1800, 'Native image source reports actual full-resolution dimensions');",
      "    $native_srcset = tk_image_opt_original_only_srcset(array(768 => array('url' => $url, 'value' => 768, 'descriptor' => 'w')), array(768, 432), $url,",
      "        array('file' => 'photo-scaled.jpg', 'width' => 2560, 'original_image' => 'photo.jpg'), 1);",
      "    check(array_keys($native_srcset) === array(3200) && $native_srcset[3200]['value'] === 3200, 'Native srcset uses original pixel width instead of scaled metadata width');",
      "    $test_files[2] = $test_dir . '/photo-e123.jpg'; copy($source, $test_files[2]);",
      "    $test_metadata[2] = array('original_image' => 'photo.jpg');",
      "    check(tk_image_opt_source_file(2) === $test_files[2], 'Deliberate WordPress image edits remain authoritative');",
      "    $thumb = $test_dir . '/photo-768x432.jpg'; copy($source, $thumb);",
      "    $unused = $test_dir . '/photo-768x432-tkopt.jpg'; copy($target, $unused);",
      "    file_put_contents($unused . '.json', '{}');",
      "    $new_unused = $thumb . '-tkopt.webp'; copy($target, $new_unused);",
      "    check(tk_image_opt_cleanup_intermediate_derivatives($source, $test_metadata[1]) === 2, 'Regeneration removes obsolete thumbnail copies in both naming formats');",
      "    check(is_file($thumb) && is_file($source) && !is_file($unused . '.json'), 'Cleanup retains original uploads and removes sidecar reports');",
      "    $legacy = 'https://cdn.example.test/site/uploads/photo-768x432-tkopt.webp';",
      "    copy($png . '-tkopt.webp', $test_dir . '/photo.webp');",
      "    check(strpos(tk_image_opt_frontend_url($legacy), 'photo-tkopt.jpg') !== false, 'Old thumbnail WebP URL resolves to full-resolution optimized image');",
      "    check(tk_image_opt_original_url_for_intermediate_url($legacy) === $url, 'Legacy lossy WebP sibling cannot displace registered original source');",
      "    check(strpos(tk_image_opt_frontend_url('https://cdn.example.test/site/uploads/photo-tkopt.webp'), 'photo-tkopt.jpg') !== false,",
      "        'Legacy full-size WebP copy resolves to JPEG source instead of another compressed WebP');",
      "",
      "    if (!empty($argv[1])) {",
      "        $wp = rtrim($argv[1], '/') . '/wp-includes/';",
      "        require_once $wp . 'class-wp-token-map.php';",
      "        foreach (array('html5-named-character-references.php', 'class-wp-html-attribute-token.php', 'class-wp-html-span.php', 'class-wp-html-text-replacement.php', 'class-wp-html-decoder.php', 'class-wp-html-tag-processor.php') as $file) {",
      "            require_once $wp . 'html-api/' . $file;",
      "        }",
      "        $script = '<script type=\"application/ld+json\">{\"image\":\"' . $url . '\"}</script>';",
      "        $html = $script . '<img class=\"lozad\" src=\"' . $url . '\" data-src=\"' . $legacy . '\" srcset=\"' . $legacy . ' 768w, ' . $url . ' 3200w\"><a href=\"' . $url . '\">Original</a>';",
      "        $rewritten = tk_image_opt_rewrite_html_buffer($html);",
      "        check(strpos($rewritten, $script) === 0 && strpos($rewritten, '<a href=\"' . $url . '\">') !== false, 'HTML rewrite preserves JSON-LD, scripts and download links');",
      "        $parser = new WP_HTML_Tag_Processor($rewritten); $parser->next_tag('IMG');",
      "        check(strpos($parser->get_attribute('data-src'), 'photo-tkopt.jpg') !== false, 'Lazy-load attributes use full-resolution validated copy');",
      "        check(substr($parser->get_attribute('srcset'), -6) === ' 3200w' && strpos($parser->get_attribute('srcset'), ',') === false, 'HTML srcset contains one accurate full-resolution candidate');",
      "        $files_before = glob($test_dir . '/*');",
      "        for ($i = 0; $i < 10; $i++) { tk_image_opt_rewrite_html_buffer($html); }",
      "        check($files_before === glob($test_dir . '/*') && hash_file('sha256', $target) === $regenerated, 'Frontend requests do not create or recompress files');",
      "    } else {",
      "        echo \"[SKIP] HTML parser integration: pass a WordPress root path.\\n\";",
      "    }",
      "    check(hash_file('sha256', $source) === $hash, 'Original source still unchanged after all workflows');",
      "    for ($id = 1; $id <= 7; $id++) { $test_files[$id] = $source; }",
      "    $test_options['image_opt_queue'] = array('status' => 'running', 'run_id' => 'test', 'offset' => 0);",
      "    $held_lock = fopen($test_dir . '/.tkopt-queue.lock', 'c'); flock($held_lock, LOCK_EX);",
      "    tk_image_opt_queue_process();",
      "    check($test_options['image_opt_queue']['offset'] === 0, 'Concurrent queue worker cannot acquire held lock');",
      "    flock($held_lock, LOCK_UN); fclose($held_lock);",
      "    tk_image_opt_queue_process();",
      "    check($test_options['image_opt_queue']['offset'] === 5 && $test_options['image_opt_queue']['status'] === 'running', 'Queue advances five attachments and schedules continuation');",
      "    tk_image_opt_queue_process();",
      "    check($test_options['image_opt_queue']['status'] === 'complete' && $test_options['image_opt_queue']['processed'] === 7, 'Queue finishes remaining attachments without skipping');",
      "    $test_options['image_opt_queue'] = array('status' => 'running', 'run_id' => 'stop-test', 'offset' => 0);",
      "    $GLOBALS['test_stop_worker'] = true;",
      "    tk_image_opt_queue_process();",
      "    check($test_options['image_opt_queue']['status'] === 'stopped' && $test_options['image_opt_queue']['offset'] === 0, 'Worker respects stop submitted during encoding');",
      "    $GLOBALS['test_stop_worker'] = false;",
      "    unlink($test_dir . '/.tkopt-queue.lock');",
      "    $test_options['webp_convert_enabled'] = 1;",
      "    $metadata = array('file' => 'photo.jpg', 'width' => 3200, 'height' => 1800, 'sizes' => array());",
      "    check(tk_webp_generate_on_metadata_update($metadata, 1) === $metadata, 'Auto WebP metadata filter preserves array and receives attachment ID correctly');",
      "    check(glob($test_dir . '/.tkopt-*') === array(), 'Encoding leaves no temporary files');",
      "    echo $passes, \" checks passed.\\n\";",
      "} finally {",
      "    foreach (glob($test_dir . '/*') as $file) { unlink($file); }",
      "    foreach (glob($test_dir . '/.tkopt-*') as $file) { unlink($file); }",
      "    rmdir($test_dir);",
      "}",
      ""
    ]
  },
  {
    "name": "lazy-media",
    "runtime": "node",
    "source": [
      "const assert = require('node:assert/strict');",
      "const fs = require('node:fs');",
      "const vm = require('node:vm');",
      "const script = fs.readFileSync(require('node:path').join(__dirname, '../includes/lazy-load.php'), 'utf8').match(/<<<'JS'\\n([\\s\\S]*?)\\nJS;/)[1];",
      "function media(tag, attributes = {}) {",
      "    return { tagName: tag, nodeType: 1, isConnected: true, children: [], attributes,",
      "        getAttribute(key) { return this.attributes[key] || null; },",
      "        setAttribute(key, value) { this.attributes[key] = value; },",
      "        removeAttribute(key) { delete this.attributes[key]; },",
      "        matches() { return !!(this.attributes['data-tk-lazy-src'] || this.attributes['data-tk-lazy-srcset']); },",
      "        querySelectorAll() { return this.children.filter(child => child.matches()); },",
      "        closest() { return this.parent; },",
      "        load() { this.loads = (this.loads || 0) + 1; }",
      "    };",
      "}",
      "for (const supported of [true, false]) {",
      "    const video = media('VIDEO');",
      "    const source = media('SOURCE', { 'data-tk-lazy-src': '/video.mp4' });",
      "    source.parent = video;",
      "    video.children = [source];",
      "    const frame = media('IFRAME', { 'data-tk-lazy-src': '/embed' });",
      "    const eager = media('IFRAME', { 'data-tk-lazy-src': '/hero', loading: 'eager' });",
      "    let ready, intersect, mutate, options;",
      "    const observed = new Set();",
      "    let observers = 0;",
      "    class IntersectionObserver {",
      "        constructor(callback, config) { intersect = callback; options = config; observers++; }",
      "        observe(node) { observed.add(node); }",
      "        unobserve(node) { observed.delete(node); }",
      "    }",
      "    class MutationObserver {",
      "        constructor(callback) { mutate = callback; }",
      "        observe() {}",
      "    }",
      "    const document = { readyState: 'loading', documentElement: {},",
      "        querySelectorAll(selector) { return selector.startsWith('script') ? [] : [source, frame, eager]; },",
      "        addEventListener(event, callback) { ready = callback; }",
      "    };",
      "    const window = { MutationObserver };",
      "    if (supported) { window.IntersectionObserver = IntersectionObserver; }",
      "    const context = vm.createContext({ window, document, IntersectionObserver, MutationObserver, WeakSet });",
      "    vm.runInContext(script, context);",
      "    assert.equal(observers, 0);",
      "    ready();",
      "    assert.equal(eager.attributes.src, '/hero');",
      "    if (supported) {",
      "        assert.equal(options.rootMargin, '200px 0px');",
      "        assert.equal(options.threshold, 0);",
      "        assert.ok(observed.has(video));",
      "        assert.ok(!observed.has(source));",
      "        intersect([{ isIntersecting: true, target: video }, { isIntersecting: true, target: frame }]);",
      "        assert.equal(video.loads, 1);",
      "        assert.ok(!observed.has(video));",
      "    }",
      "    assert.equal(source.attributes.src, '/video.mp4');",
      "    assert.equal(frame.attributes.src, '/embed');",
      "    assert.equal(source.attributes['data-tk-lazy-src'], undefined);",
      "    const inserted = media('IFRAME', { 'data-tk-lazy-src': '/new' });",
      "    mutate([{ type: 'childList', addedNodes: [inserted], removedNodes: [] }]);",
      "    if (supported) {",
      "        assert.ok(observed.has(inserted));",
      "        intersect([{ isIntersecting: true, target: inserted }]);",
      "    }",
      "    assert.equal(inserted.attributes.src, '/new');",
      "    vm.runInContext(script, context);",
      "    assert.equal(observers, supported ? 1 : 0);",
      "}",
      "console.log('PASS: DOM readiness, video/source grouping, eager media, dynamic insertion, fallback and single initialization');",
      ""
    ]
  },
  {
    "name": "lazy-priority",
    "runtime": "php",
    "source": [
      "<?php",
      "define('ABSPATH', '/tmp/');",
      "function tk_license_features_enabled() { return true; }",
      "function tk_get_option($key, $default = null) { return $key === 'lazy_load_enabled' ? 1 : ($key === 'lazy_load_eager_images' ? 0 : $default); }",
      "function esc_attr($value) { return htmlspecialchars($value, ENT_QUOTES); }",
      "require dirname(__DIR__) . '/includes/lazy-load.php';",
      "$attributes = tk_lazy_image_attributes(array('loading' => 'eager', 'fetchpriority' => 'high'), null, null);",
      "if ($attributes['loading'] !== 'eager' || $attributes['fetchpriority'] !== 'high') { throw new RuntimeException('Explicit LCP priority was overwritten'); }",
      "$hero = '<img src=\"hero.jpg\" fetchpriority=\"high\">';",
      "if (tk_lazy_html_buffer($hero) !== $hero) { throw new RuntimeException('High-priority HTML image was modified'); }",
      "$iframe = '<iframe loading=\"eager\" src=\"hero.html\"></iframe>';",
      "if (tk_lazy_oembed_iframe($iframe, '', array(), 1) !== $iframe) { throw new RuntimeException('Eager iframe was deferred'); }",
      "echo \"PASS: explicit LCP image priority and eager iframe preserved\\n\";",
      ""
    ]
  },
  {
    "name": "meta-description",
    "runtime": "php",
    "source": [
      "<?php",
      "define('ABSPATH', '/tmp/');",
      "$excerpt = '';",
      "$content = '[tool_kits_geo_faq] Adventure Travel & Nature Getaways';",
      "function is_singular() { return true; }",
      "function get_the_excerpt() { return $GLOBALS['excerpt']; }",
      "function get_post() { return (object) array('post_content' => $GLOBALS['content']); }",
      "function wp_strip_all_tags($text) { return strip_tags($text); }",
      "function strip_shortcodes($text) { return str_replace('[tool_kits_geo_faq]', '', $text); }",
      "function get_bloginfo($key) { return 'Site description'; }",
      "require dirname(__DIR__) . '/includes/seo-optimization.php';",
      "function verify($expected) {",
      "    if (tk_seo_generate_description() !== $expected) { throw new RuntimeException('Description regression'); }",
      "}",
      "verify('Adventure Travel & Nature Getaways');",
      "$excerpt = '[tool_kits_geo_faq] <p>Manual description</p>';",
      "verify('Manual description');",
      "$excerpt = '';",
      "$content = '[tool_kits_geo_faq]';",
      "verify('Site description');",
      "echo \"PASS: shortcode excluded from content/excerpt descriptions and fallback\\n\";",
      ""
    ]
  },
  {
    "name": "monitoring-cache-performance",
    "runtime": "php",
    "source": [
      "<?php",
      "define('ABSPATH', '/tmp/');",
      "define('WP_CONTENT_DIR', '/nonexistent-tool-kits-test');",
      "$cache = array();",
      "$writes = 0;",
      "$hooks = array();",
      "function get_transient($key) { return $GLOBALS['cache'][$key] ?? false; }",
      "function set_transient($key, $value, $ttl) { $GLOBALS['cache'][$key] = $value; $GLOBALS['writes']++; }",
      "function trailingslashit($path) { return rtrim($path, '/') . '/'; }",
      "function add_action($hook, $callback, $priority = 10, $args = 1) { $GLOBALS['hooks'][] = array($hook, $callback, $priority); }",
      "require dirname(__DIR__) . '/includes/monitoring-404-health.php';",
      "require dirname(__DIR__) . '/includes/cache.php';",
      "function verify($condition, $message) { if (!$condition) { throw new RuntimeException($message); } }",
      "tk_error_rate_recent(300);",
      "tk_error_rate_recent(300);",
      "verify($writes === 1, 'Repeated error-rate read should use cache');",
      "tk_page_cache_purge_on_meta_change(1, 2, '_tk_seo_rendered_audit', array());",
      "tk_page_cache_purge_on_meta_change(1, 2, '_edit_lock', 'lock');",
      "verify($hooks === array(), 'Internal metadata must not purge page cache');",
      "tk_page_cache_purge_on_meta_change(1, 2, '_tk_geo_faq_items', array());",
      "tk_page_cache_purge_once();",
      "tk_page_cache_purge_on_content_change();",
      "verify(count($hooks) === 1 && $hooks[0] === array('shutdown', 'tk_page_cache_purge', PHP_INT_MAX), 'Content changes must queue a single final purge');",
      "echo \"PASS: error-rate cache, ignored internal metadata, deferred single purge\\n\";",
      ""
    ]
  },
  {
    "name": "monitoring-ui",
    "runtime": "node",
    "source": [
      "const { chromium } = require(process.env.TK_PLAYWRIGHT_MODULE || 'playwright');",
      "const assert = require('node:assert/strict');",
      "",
      "(async () => {",
      "    const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--allow-file-access-from-files'] });",
      "    try {",
      "        const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });",
      "        const errors = [];",
      "        const consoleMessages = [];",
      "        page.on('pageerror', error => errors.push(error.message));",
      "        page.on('console', message => consoleMessages.push(message.text()));",
      "        await page.addInitScript(() => {",
      "            window.calls = 0;",
      "            window.aborts = 0;",
      "            window.testHidden = false;",
      "            Object.defineProperty(document, 'hidden', { get: () => window.testHidden });",
      "            window.fetch = (url, options) => {",
      "                window.calls++;",
      "                window.requestUrl = url;",
      "                window.requestBody = options.body;",
      "                return new Promise((resolve, reject) => {",
      "                    window.respond = (data, ok = true) => resolve({ ok, status: ok ? 200 : 500, json: async () => data });",
      "                    options.signal.addEventListener('abort', () => {",
      "                        window.aborts++;",
      "                        reject(new DOMException('Aborted', 'AbortError'));",
      "                    });",
      "                });",
      "            };",
      "            window.sample = { success: true, data: { load: [1, 0.8, 0.6], cpu_cores: 4, memory: { used: 67108864, limit: 268435456, percent: 25 }, errors: { available: true, per_min: 0 } } };",
      "        });",
      "        const url = 'file:///tmp/toolkits-monitoring-preview.html?page=tool-kits-monitoring';",
      "        await page.goto(url + '#invalid');",
      "        const loadedAssets = await page.evaluate(() => ({",
      "            scripts: Array.from(document.scripts, script => script.src),",
      "            styles: Array.from(document.querySelectorAll('link[rel=\"stylesheet\"]'), link => link.href)",
      "        }));",
      "        assert.ok(loadedAssets.scripts.some(src => src.endsWith('/assets/health-monitor-chart.js')), 'Current Monitoring controller is loaded');",
      "        assert.ok(loadedAssets.styles.some(href => href.endsWith('/assets/tool-kits-admin-ui.css')), 'Current admin stylesheet is loaded');",
      "        assert.equal(loadedAssets.scripts.some(src => src.endsWith('/assets/monitoring-tabs.js')), false, 'Legacy Monitoring controller is not loaded');",
      "        assert.equal(loadedAssets.styles.some(href => href.endsWith('/assets/admin-layout.css')), false, 'Legacy admin stylesheet is not loaded');",
      "        await page.waitForFunction(() => window.calls === 1);",
      "        assert.equal(await page.locator('#tk-rt-cpu-plot').getAttribute('aria-busy'), 'true');",
      "        assert.equal(await page.locator('#tk-rt-cpu-state').isVisible(), true);",
      "        const heading = await page.locator('.tk-page-heading').evaluate(el => {",
      "            const style = getComputedStyle(el);",
      "            return { bg: style.backgroundColor, radius: style.borderRadius, border: style.borderTopWidth, cardClass: el.classList.contains('tk-card') };",
      "        });",
      "        assert.deepEqual(heading, { bg: 'rgb(255, 255, 255)', radius: '8px', border: '1px', cardClass: true });",
      "        const height = (await page.locator('.tk-rt-charts').boundingBox()).height;",
      "        await page.screenshot({ path: '/tmp/toolkits-monitoring-loading.png', fullPage: true });",
      "        await page.waitForTimeout(5500);",
      "        assert.equal(await page.evaluate(() => window.calls), 1, 'A slow fetch must not overlap');",
      "        await page.evaluate(() => window.respond(window.sample));",
      "        await page.waitForFunction(() => document.getElementById('tk-rt-cpu-plot').getAttribute('aria-busy') === 'false');",
      "        const firstChartState = await page.evaluate(() => {",
      "            const cpu = Chart.getChart(document.getElementById('tk-rt-cpu-chart'));",
      "            const mem = Chart.getChart(document.getElementById('tk-rt-mem-chart'));",
      "            return {",
      "                version: Chart.version,",
      "                cpuType: cpu.config.type,",
      "                cpuValues: cpu.data.datasets[0].data,",
      "                cpuMax: cpu.options.scales.y.max,",
      "                memMax: mem.options.scales.y.max,",
      "                canvasWidth: cpu.canvas.width,",
      "                canvasHeight: cpu.canvas.height",
      "            };",
      "        });",
      "        assert.equal(firstChartState.version, '4.5.1');",
      "        assert.equal(firstChartState.cpuType, 'line');",
      "        assert.equal(firstChartState.cpuValues.filter(Number.isFinite).length, 1, 'First actual sample is rendered by Chart.js');",
      "        assert.equal(firstChartState.cpuValues[29], 25, 'First sample is anchored at the latest rolling-window slot');",
      "        assert.ok(firstChartState.canvasWidth > 0 && firstChartState.canvasHeight > 0, 'Chart.js canvas has a rendered bitmap');",
      "        assert.equal(await page.locator('#tk-rt-cpu-state').isVisible(), false);",
      "        assert.ok(Math.abs((await page.locator('.tk-rt-charts').boundingBox()).height - height) < 0.5, 'Loading does not shift chart layout');",
      "        assert.equal(await page.locator('#tk-rt-cpu-avg').textContent(), '25%');",
      "        assert.equal(firstChartState.cpuMax, 100);",
      "        assert.equal(firstChartState.memMax, 256);",
      "        assert.match(await page.locator('#tk-rt-load').textContent(), /s$/);",
      "        assert.equal(await page.evaluate(() => new URLSearchParams(window.requestBody).get('nonce')), 'preview');",
      "        await page.waitForFunction(() => window.calls === 2, { timeout: 8000 });",
      "        await page.evaluate(() => { window.sample.data.load[0] = 2; window.respond(window.sample); });",
      "        await page.waitForTimeout(400);",
      "        const plottedValues = await page.evaluate(() => Chart.getChart(document.getElementById('tk-rt-cpu-chart')).data.datasets[0].data);",
      "        assert.deepEqual(plottedValues.slice(0, 28), new Array(28).fill(null), 'Unused rolling-window slots remain empty');",
      "        assert.deepEqual(plottedValues.slice(28), [25, 50], 'Initial samples stay right-aligned and chronological');",
      "        const desktopMetricBoxes = await page.locator('[data-panel-id=\"realtime\"] .tk-rt-card').evaluateAll(elements => elements.map(el => el.getBoundingClientRect().toJSON()));",
      "        assert.equal(new Set(desktopMetricBoxes.map(box => Math.round(box.top))).size, 1, 'Desktop metrics stay on one row');",
      "        const desktopChartBoxes = await page.locator('.tk-rt-chart-section').evaluateAll(elements => elements.map(el => el.getBoundingClientRect().toJSON()));",
      "        assert.ok(Math.abs(desktopChartBoxes[0].height - desktopChartBoxes[1].height) < 1, 'Desktop chart panels have matching heights');",
      "        assert.ok(desktopChartBoxes[0].right < desktopChartBoxes[1].left, 'Desktop chart panels do not overlap');",
      "        await page.screenshot({ path: '/tmp/toolkits-monitoring-desktop.png', fullPage: true });",
      "        for (const width of [390, 320]) {",
      "            await page.setViewportSize({ width, height: 844 });",
      "            assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'No overflow at ' + width);",
      "            const mobileChartBoxes = await page.locator('.tk-rt-chart-section').evaluateAll(elements => elements.map(el => el.getBoundingClientRect().toJSON()));",
      "            assert.ok(mobileChartBoxes[0].bottom < mobileChartBoxes[1].top, 'Mobile chart panels stack without overlap at ' + width);",
      "            await page.screenshot({ path: '/tmp/toolkits-monitoring-' + width + '.png', fullPage: true });",
      "        }",
      "        await page.setViewportSize({ width: 1440, height: 1100 });",
      "        await page.locator('[data-panel=\"health\"]').click();",
      "        await page.reload();",
      "        assert.equal(await page.locator('[data-panel-id=\"health\"]').isVisible(), true);",
      "        await page.waitForTimeout(150);",
      "        assert.equal(await page.evaluate(() => window.calls), 0, 'Saved non-realtime tab does not poll');",
      "        await page.evaluate(() => history.replaceState(null, '', location.pathname + location.search));",
      "        await page.reload();",
      "        assert.equal(await page.locator('[data-panel-id=\"health\"]').isVisible(), true, 'Session storage restores the tab without a hash');",
      "        await page.locator('[data-panel=\"realtime\"]').click();",
      "        await page.waitForFunction(() => window.calls === 1);",
      "        await page.locator('[data-panel=\"checks\"]').click();",
      "        assert.equal(await page.evaluate(() => window.aborts), 1, 'Tab switch cancels the request');",
      "        await page.locator('[data-panel=\"realtime\"]').click();",
      "        await page.waitForFunction(() => window.calls === 2);",
      "        await page.evaluate(() => { window.testHidden = true; document.dispatchEvent(new Event('visibilitychange')); });",
      "        assert.equal(await page.evaluate(() => window.aborts), 2, 'Hidden page cancels the request');",
      "        await page.evaluate(() => { window.testHidden = false; document.dispatchEvent(new Event('visibilitychange')); });",
      "        await page.waitForFunction(() => window.calls === 3);",
      "        await page.evaluate(() => window.respond({}, false));",
      "        await page.waitForFunction(() => !document.getElementById('tk-rt-retry').hidden);",
      "        assert.equal(await page.locator('#tk-rt-cpu-plot').getAttribute('aria-busy'), 'false');",
      "        assert.match(await page.locator('#tk-rt-cpu-state').textContent(), /could not/);",
      "        await page.locator('#tk-rt-retry').click();",
      "        await page.waitForFunction(() => window.calls === 4);",
      "        await page.evaluate(() => window.respond({ success: false, data: { message: 'forbidden' } }));",
      "        await page.waitForFunction(() => !document.getElementById('tk-rt-retry').hidden);",
      "        await page.locator('#tk-rt-retry').click();",
      "        await page.waitForFunction(() => window.calls === 5);",
      "        await page.evaluate(() => { window.sample.data.load = null; window.respond(window.sample); });",
      "        await page.waitForFunction(() => document.getElementById('tk-rt-cpu-state').textContent.includes('unavailable'));",
      "        assert.ok(await page.evaluate(() => Chart.getChart(document.getElementById('tk-rt-mem-chart')).data.datasets[0].data.some(Number.isFinite)));",
      "        await page.emulateMedia({ reducedMotion: 'reduce' });",
      "        assert.equal(await page.locator('#tk-rt-pulse').evaluate(el => getComputedStyle(el).animationName), 'none');",
      "        assert.deepEqual(errors, []);",
      "        assert.deepEqual(consoleMessages.filter(message => message.startsWith('ToolKits:')), []);",
      "        console.log('PASS: Chart.js 4.5.1, cache-busted assets, header card, loading, rolling samples, responsive layout, tab persistence, cancellation, errors, retry, missing CPU, reduced motion.');",
      "    } finally {",
      "        await browser.close();",
      "    }",
      "})().catch(error => { console.error(error); process.exitCode = 1; });",
      ""
    ]
  },
  {
    "name": "monitoring",
    "runtime": "php",
    "source": [
      "<?php",
      "// Isolated regression checks: no WordPress installation or database is bootstrapped.",
      "if (PHP_SAPI !== 'cli') { exit; }",
      "define('ABSPATH', __DIR__ . '/');",
      "define('WP_CONTENT_DIR', __DIR__ . '/nonexistent-content');",
      "define('HOUR_IN_SECONDS', 3600);",
      "define('AUTH_KEY', 'isolated-test-key');",
      "$options = array('tk_options' => array(",
      "    'license_status' => 'valid', 'license_last_checked' => time(),",
      "    'license_key' => 'fixture', 'license_site_url' => 'https://example.test',",
      "    'toolkits_install_id' => 'fixture-install',",
      "));",
      "$transients = array('tk_healthcheck_cpu_cores' => 4);",
      "$allowed = true;",
      "$nonce_valid = true;",
      "function get_option($key, $default = false) { return $GLOBALS['options'][$key] ?? $default; }",
      "function update_option($key, $value, $autoload = null) { $GLOBALS['options'][$key] = $value; }",
      "function get_transient($key) { return $GLOBALS['transients'][$key] ?? false; }",
      "function set_transient($key, $value, $ttl) { $GLOBALS['transients'][$key] = $value; }",
      "function add_action(...$args) {}",
      "function add_filter(...$args) {}",
      "function is_admin() { return false; }",
      "function home_url($path = '/') { return 'https://example.test' . $path; }",
      "function wp_parse_url($url) { return parse_url($url); }",
      "function wp_json_encode($data) { return json_encode($data); }",
      "function untrailingslashit($value) { return rtrim($value, '/'); }",
      "function trailingslashit($value) { return rtrim($value, '/') . '/'; }",
      "function get_plugins() { throw new RuntimeException('Unexpected plugin filesystem scan'); }",
      "function current_user_can($capability) { return $GLOBALS['allowed']; }",
      "function check_ajax_referer($action, $name) {",
      "    if ($action !== 'tk_realtime_health' || $name !== 'nonce' || !$GLOBALS['nonce_valid']) throw new RuntimeException('Invalid nonce');",
      "}",
      "class MonitoringResponse extends RuntimeException {",
      "    public $data;",
      "    public function __construct($data) { $this->data = $data; }",
      "}",
      "function wp_send_json_success($data) { throw new MonitoringResponse(array('success' => true, 'data' => $data)); }",
      "function wp_send_json_error($data) { throw new MonitoringResponse(array('success' => false, 'data' => $data)); }",
      "require dirname(__DIR__) . '/includes/helpers.php';",
      "require dirname(__DIR__) . '/includes/monitoring-404-health.php';",
      "$checks = 0;",
      "function verify($condition, $label) {",
      "    if (!$condition) throw new RuntimeException('FAIL: ' . $label);",
      "    $GLOBALS['checks']++;",
      "    echo 'PASS: ', $label, PHP_EOL;",
      "}",
      "$options['tk_options']['license_signature'] = tk_license_expected_signature();",
      "verify(tk_license_validate()['status'] === 'valid', 'Signed cached license validates without a network call');",
      "$options['tk_options']['license_signature'] = 'tampered';",
      "verify(tk_license_validate()['status'] === 'integrity_violation', 'Cached license still enforces signature integrity');",
      "verify(tk_healthcheck_cpu_cores() === 4, 'CPU capacity uses its cached value');",
      "$transients['tk_healthcheck_cpu_cores'] = 0;",
      "verify(tk_healthcheck_cpu_cores() === null, 'Unavailable CPU capacity is cached without shell retries');",
      "$transients['tk_healthcheck_cpu_cores'] = 4;",
      "$data = tk_realtime_health_data(false);",
      "verify($data['heavy_plugins'] === array(), 'Lightweight metrics do not enumerate plugins');",
      "verify($data['memory']['used'] > 0 && $data['cpu_cores'] === 4, 'Lightweight metrics retain memory and CPU data');",
      "try { tk_realtime_health_ajax(); } catch (MonitoringResponse $response) {",
      "    verify($response->data['success'] && $response->data['data']['heavy_plugins'] === array(), 'AJAX uses the lightweight path');",
      "}",
      "$allowed = false;",
      "try { tk_realtime_health_ajax(); } catch (MonitoringResponse $response) {",
      "    verify(!$response->data['success'], 'Unauthorized users cannot fetch metrics');",
      "}",
      "$allowed = true;",
      "$nonce_valid = false;",
      "try { tk_realtime_health_ajax(); throw new LogicException('Nonce was not checked'); } catch (RuntimeException $error) {",
      "    verify($error->getMessage() === 'Invalid nonce', 'Invalid nonce is rejected before collecting metrics');",
      "}",
      "echo $checks, \" monitoring regression checks passed.\\n\";",
      ""
    ]
  },
  {
    "name": "post-faq-rendered",
    "runtime": "php",
    "source": [
      "<?php",
      "define('ABSPATH', '/tmp/');",
      "$meta = array();",
      "$valid_nonce = true;",
      "$can_edit = true;",
      "function wp_is_post_revision($id) { return false; }",
      "function wp_is_post_autosave($id) { return false; }",
      "function wp_verify_nonce($nonce, $action) { return $GLOBALS['valid_nonce']; }",
      "function current_user_can($cap, $id) { return $GLOBALS['can_edit']; }",
      "function sanitize_text_field($text) { return strip_tags($text); }",
      "function esc_url_raw($text) { return $text; }",
      "function get_post_type($id) { return 'page'; }",
      "function get_post_types($args, $output) {",
      "    if ($output === 'names') { return array('page' => 'page'); }",
      "    return array('page' => (object) array('name' => 'page'), 'section' => (object) array('name' => 'section'));",
      "}",
      "function get_posts($args) { $GLOBALS['bulk_queries']++; return array(); }",
      "function get_post($id) { return null; }",
      "function home_url($path) { return 'https://example.com/'; }",
      "function wp_parse_url($url, $component = -1) { return parse_url($url, $component); }",
      "function is_post_type_viewable($type) { return $type->name === 'page'; }",
      "function tk_get_option($key, $default = null) { return $GLOBALS['selected_types'] ?? $default; }",
      "function wp_unslash($text) { return stripslashes($text); }",
      "function wp_strip_all_tags($text) { return strip_tags($text); }",
      "function update_post_meta($id, $key, $value) { $GLOBALS['meta'][$id][$key] = $value; }",
      "function delete_post_meta($id, $key) { unset($GLOBALS['meta'][$id][$key]); }",
      "require dirname(__DIR__) . '/includes/seo-optimization.php';",
      "require dirname(__DIR__) . '/includes/geo.php';",
      "function verify($condition, $message) { if (!$condition) { throw new RuntimeException($message); } }",
      "$post = (object) array('ID' => 1);",
      "verify(tk_seo_selected_post_types() === array('page'), 'Sections excluded by default');",
      "$selected_types = array();",
      "verify(tk_seo_selected_post_types() === array(), 'Explicit deselect all preserved');",
      "$selected_types = array('page', 'invalid');",
      "verify(tk_seo_selected_post_types() === array('page'), 'Unknown types ignored');",
      "$_POST = array('tk_seo_geo_meta_nonce' => 'test', 'tk_geo_post_faq' => addslashes(json_encode(array(array('question' => '<b>Who?</b>', 'answer' => 'Team \"A\"')))));",
      "tk_seo_save_geo_meta_box(1, $post);",
      "verify($meta[1]['_tk_geo_faq_items'][0] === array('question' => 'Who?', 'answer' => 'Team \"A\"'), 'Save and sanitize FAQ');",
      "unset($_POST['tk_geo_post_faq']);",
      "tk_seo_save_geo_meta_box(1, $post);",
      "verify(count($meta[1]['_tk_geo_faq_items']) === 1, 'Untouched popup preserves FAQ');",
      "$_POST['tk_geo_post_faq'] = '[]';",
      "$valid_nonce = false;",
      "tk_seo_save_geo_meta_box(1, $post);",
      "verify(count($meta[1]['_tk_geo_faq_items']) === 1, 'Invalid nonce rejected');",
      "$valid_nonce = true;",
      "$can_edit = false;",
      "tk_seo_save_geo_meta_box(1, $post);",
      "verify(count($meta[1]['_tk_geo_faq_items']) === 1, 'Missing edit permission rejected');",
      "$can_edit = true;",
      "$_POST['tk_geo_post_faq'] = '{invalid';",
      "tk_seo_save_geo_meta_box(1, $post);",
      "verify(count($meta[1]['_tk_geo_faq_items']) === 1, 'Invalid JSON preserves FAQ');",
      "$_POST['tk_geo_post_faq'] = '[]';",
      "tk_seo_save_geo_meta_box(1, $post);",
      "verify($meta[1]['_tk_geo_faq_items'] === array(), 'Remove all FAQ');",
      "$faq_rows = array_fill(0, 55, array('question' => 'Question?', 'answer' => 'Answer'));",
      "verify(count(tk_geo_normalize_faq_items(array_slice($faq_rows, 0, 30))) === 30, 'More than 20 FAQ retained');",
      "verify(count(tk_geo_normalize_faq_items($faq_rows)) === 50, 'FAQ capped at 50');",
      "$translated = tk_geo_normalize_faq_items(array(",
      "    array('question' => 'Indonesia?', 'answer' => 'Ya', 'language' => 'id_ID'),",
      "    array('question' => 'English?', 'answer' => 'Yes', 'language' => 'en'),",
      "    array('question' => 'Legacy?', 'answer' => 'Fallback'),",
      "));",
      "verify($translated[0]['language'] === 'id-id', 'Locale normalization');",
      "verify(count(tk_geo_faq_items_for_language($translated, 'en_SG')) === 2, 'English and fallback selection');",
      "verify(count(tk_geo_faq_items_for_language($translated, 'id_ID')) === 2, 'Indonesian selection');",
      "$html = '<html><head><title>Builder page</title><meta content=\"Description\" name=\"description\"><link href=\"https://example.com/page\" rel=\"canonical\"></head><body><nav>Navigation</nav><main><h1>Builder</h1><p>Custom field text</p><img alt=\"\" src=\"a.jpg\"><script>hidden script</script></main></body></html>';",
      "$report = tk_seo_parse_rendered_audit($html);",
      "verify($report['score'] === 100 && $report['issues'] === array(), 'Valid rendered page');",
      "verify(strpos($report['text_sample'], 'Custom field text') !== false && strpos($report['text_sample'], 'Navigation') === false && strpos($report['text_sample'], 'hidden script') === false, 'Main text extraction');",
      "$report = tk_seo_parse_rendered_audit('<html><body><h1>First</h1><h1>Second</h1><img src=\"a.jpg\"></body></html>');",
      "verify($report['score'] < 100 && $report['h1_count'] === 2 && count($report['issues']) === 6, 'Rendered issues detected');",
      "$bulk_queries = 0;",
      "tk_seo_run_content_audit(999);",
      "verify($bulk_queries === 0, 'Editor audit must not query all posts');",
      "tk_seo_run_content_audit();",
      "verify($bulk_queries === 1, 'Full audit retains bulk query');",
      "echo \"PASS: FAQ persistence/security and rendered HTML audit\\n\";",
      ""
    ]
  },
  {
    "name": "updater-scope",
    "runtime": "php",
    "source": [
      "<?php",
      "define('ABSPATH', '/tmp/');",
      "define('TK_PATH', '/tmp/tool-kits/');",
      "$admin = false;",
      "$cron = false;",
      "$ajax = false;",
      "$cache = array();",
      "function add_action() {}",
      "function add_filter() {}",
      "function plugin_basename($path) { return 'tool-kits/tool-kits.php'; }",
      "function current_user_can($cap) { return true; }",
      "function wp_doing_cron() { return $GLOBALS['cron']; }",
      "function wp_doing_ajax() { return $GLOBALS['ajax']; }",
      "function is_admin() { return $GLOBALS['admin']; }",
      "function get_transient($key) { return $GLOBALS['cache'][$key] ?? false; }",
      "class WP_Error { public $code; public function __construct($code, $message) { $this->code = $code; } }",
      "require dirname(__DIR__) . '/includes/github-update-check.php';",
      "function verify($condition) { if (!$condition) { throw new RuntimeException('Updater scope regression'); } }",
      "verify(tk_github_updater_enabled());",
      "verify(tk_github_fetch_latest_release()->code === 'tk_github_check_deferred');",
      "$state = (object) array('checked' => array('tool-kits/tool-kits.php' => '1'), 'response' => array('tool-kits/tool-kits.php' => (object) array()));",
      "verify(tk_github_plugin_update_check($state) === $state && isset($state->response['tool-kits/tool-kits.php']));",
      "$admin = true;",
      "$pagenow = 'plugins.php';",
      "verify(tk_github_can_check_remote());",
      "$cron = true;",
      "verify(!tk_github_can_check_remote());",
      "$cron = false;",
      "$ajax = true;",
      "verify(!tk_github_can_check_remote());",
      "$ajax = false;",
      "$pagenow = 'index.php';",
      "verify(!tk_github_can_check_remote());",
      "$pagenow = 'plugins.php';",
      "$cache['tk_github_check_cooldown'] = 1;",
      "verify(tk_github_fetch_latest_release()->code === 'tk_github_check_cooldown');",
      "echo \"PASS: Plugins-only remote checks, frontend/cron/AJAX exclusions, preserved offers, failure cooldown\\n\";",
      ""
    ]
  }
];
const requested = process.argv[2];
if (requested === '--list') {
    cases.forEach(test => console.log(test.name));
    process.exit(0);
}
const optional = new Set(['image-optimizer', 'image-optimizer-no-imagick', 'monitoring-ui']);
const selected = requested ? cases.filter(test => test.name === requested) : cases.filter(test => !optional.has(test.name));
if (!selected.length) { console.error('Unknown test: ' + requested); process.exit(1); }
let failures = 0;
for (const test of selected) {
    console.log('\nRunning ' + test.name);
    let code = test.source.join('\n');
    let command, args;
    if (test.runtime === 'php') {
        const directory = "'" + __dirname.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
        code = code.replace(/^<\?php\s*/, '').replace(/\b__DIR__\b/g, directory);
        command = process.env.TK_PHP_BINARY || 'php';
        args = ['-r', code, ...process.argv.slice(3)];
    } else {
        command = process.execPath;
        code = '(function(__dirname) {\n' + code + '\n})(' + JSON.stringify(__dirname) + ');';
        args = ['-e', code, ...process.argv.slice(3)];
    }
    const result = spawnSync(command, args, { cwd: __dirname, stdio: 'inherit' });
    if (result.error) { console.error(result.error.message); }
    if (result.status !== 0 || result.error) { failures++; }
}
if (!requested) { console.log('\nOptional integration cases: ' + [...optional].join(', ')); }
console.log('\n' + (selected.length - failures) + '/' + selected.length + ' cases passed.');
process.exitCode = failures ? 1 : 0;
